--EXAMEN PLSQL JOSE MARIA VIUDEZ PARRA

--1.
CREATE OR REPLACE TRIGGER EJ1
BEFORE UPDATE OF CANTIDADENSTOCK ON JPRODUCTOS
FOR EACH ROW
BEGIN
 IF :NEW.CANTIDADENSTOCK<0 THEN
  :NEW.CANTIDADENSTOCK:=0;
 END IF;
END;

--2.
ALTER TABLE JUGADORES ADD RANKING NUMBER(4);

CREATE OR REPLACE PROCEDURE EJ2
AS
 CURSOR C IS SELECT JUGADOR,AVG(PUNTOS_POR_PARTIDO) AS MEDIA FROM ESTADISTICAS GROUP BY JUGADOR ORDER BY MEDIA;
 NUMERO NUMBER(8) DEFAULT 1;
BEGIN
 COMMIT;
 FOR F IN C LOOP
  UPDATE JUGADORES SET RANKING=NUMERO WHERE CODIGO=F.JUGADOR;
  NUMERO:=NUMERO+1;
  COMMIT;
 END LOOP;
END;

EXECUTE EJ2;

--3.
CREATE OR REPLACE PROCEDURE EJ3(COD JUGADORES.CODIGO%TYPE)
AS
 CURSOR C1 IS SELECT J.CODIGO,J.NOMBRE NOMBRE_JUGADOR ,J.PROCEDENCIA,J.ALTURA,J.PESO,J.POSICION,
 J.NOMBRE_EQUIPO,E.CIUDAD,E.CONFERENCIA,E.DIVISION,J.RANKING
 FROM JUGADORES J INNER JOIN EQUIPOS E ON J.NOMBRE_EQUIPO=E.NOMBRE WHERE J.CODIGO=COD;
BEGIN
EJ2;
FOR F IN C1 LOOP
 DBMS_OUTPUT.PUT_LINE('DATOS DEL JUGADOR: '||COD);
 DBMS_OUTPUT.PUT_LINE(F.CODIGO||' '||F.NOMBRE_JUGADOR||' '||F.PROCEDENCIA||' '||F.ALTURA||' '||F.PESO||' '||F.POSICION);
 DBMS_OUTPUT.PUT_LINE(' ');
 DBMS_OUTPUT.PUT_LINE('DATOS DEL EQUIPO DEL JUGADOR: '||COD);
 DBMS_OUTPUT.PUT_LINE(F.NOMBRE_EQUIPO||' '||F.CIUDAD||' '||F.CONFERENCIA||' '||F.DIVISION||' '||F.RANKING);
END LOOP;
EXCEPTION
 WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('EL JUGADOR NO EXISTE');
END;

EXECUTE EJ3(1);

--4.
CREATE OR REPLACE PROCEDURE EJ4
AS
CURSOR C IS SELECT CODIGOCLIENTE,SUM(CANTIDAD) AS TOTAL_PAGO FROM JPAGOS GROUP BY CODIGOCLIENTE;
BEGIN
 COMMIT;
 FOR F IN C LOOP
  IF F.TOTAL_PAGO>10000 THEN
   UPDATE JCLIENTES SET LIMITECREDITO=LIMITECREDITO*1.3 WHERE CODIGOCLIENTE=F.CODIGOCLIENTE;
  END IF;
  COMMIT;
 END LOOP;
END;

EXECUTE EJ4;

--5.
CREATE OR REPLACE PROCEDURE EJ5
AS
 CURSOR C IS SELECT ROWID,SALARIO FROM EMPLE;
 SUBIDA NUMBER(6,2);
 AÑOS_ANTIGUEDAD NUMBER(3);
BEGIN
 COMMIT;
 FOR F IN C LOOP
  SELECT MONTHS_BETWEEN(CURRENT_DATE,FECHA_ALT)/12 INTO AÑOS_ANTIGUEDAD FROM EMPLE WHERE ROWID=F.ROWID;
  SUBIDA:=AÑOS_ANTIGUEDAD*10;
  IF F.SALARIO+SUBIDA<=3000 AND F.SALARIO+SUBIDA>=1000 THEN
   UPDATE EMPLE SET SALARIO=SALARIO+SUBIDA WHERE ROWID=F.ROWID;
  END IF;
  COMMIT;
 END LOOP;
END;

EXECUTE EJ5;

