--EXAMEN JUNIO 2018 PL/SQL 

--1
CREATE OR REPLACE FUNCTION EX_2018_1(CODSUC EB_SUCURSALES.CODSUCURSAL%TYPE)
RETURN VARCHAR2
AS
 DIRSUC VARCHAR2(40);
 POBSUC VARCHAR2(30);
 TELSUC VARCHAR2(9);
 NUMERO_CUENTAS NUMBER(5);
BEGIN
 SELECT DIRSUCURSAL,POBSUCURSAL,TELSUCURSAL INTO DIRSUC,POBSUC,TELSUC FROM
 EB_SUCURSALES WHERE CODSUCURSAL=CODSUC;
 SELECT COUNT(*) INTO NUMERO_CUENTAS FROM EB_CUENTAS WHERE SUCURSAL=CODSUC;
 RETURN DIRSUC||' - '||POBSUC||' - '||TELSUC||' - '||NUMERO_CUENTAS;
EXCEPTION
 WHEN NO_DATA_FOUND THEN
  RETURN 'LA SUCURSAL NO EXISTE';
END;

SELECT EX_2018_1('0000'1) FROM DUAL

--2
CREATE OR REPLACE PROCEDURE EX_2018_2(DNI VARCHAR2,TC VARCHAR2)
AS
 NC EB_CLIENTES.NOMCLI%TYPE;
 AC VARCHAR2(25);
 DC VARCHAR2(30);
 CURSOR CUENTAS_T IS SELECT * FROM EB_CUENTAS WHERE CLITITULAR=DNI
 AND TIPO=TC;
 CURSOR CUENTAS_A IS SELECT * FROM EB_CUENTAS WHERE CLIAUTORIZADO=DNI
 AND TIPO=TC;
BEGIN
 SELECT NOMCLI,APECLI,DIRCLI INTO NC,AC,DC FROM EB_CLIENTES 
 WHERE DNICLI=DNI;
 DBMS_OUTPUT.PUT_LINE(NC||' '||AC||' '||DC);
 DBMS_OUTPUT.PUT_LINE('CUENTAS EN LAS QUE EL CLIENTE ES TITULAR');
 FOR F IN CUENTAS_T LOOP
  DBMS_OUTPUT.PUT_LINE(F.NUMEROCTA||' '||F.SUCURSAL||' '||F.FECHAAPERTURA);
 END LOOP;
 DBMS_OUTPUT.PUT_LINE('CUENTAS EN LAS QUE EL CLIENTE ES AUTORIZADO');
 FOR F IN CUENTAS_A LOOP
  DBMS_OUTPUT.PUT_LINE(F.NUMEROCTA||' '||F.SUCURSAL||' '||F.FECHAAPERTURA);
 END LOOP;
EXCEPTION
 WHEN NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE('CLIENTE INEXISTENTE');
END;

--3

--PESCADIÑA Q SE MUERDE LA COLA -> LA TABLA ESTÁ MUTANDO
--SOLUCION TABLA AUTÓNOMA
CREATE OR REPLACE TRIGGER EX_2018_3
BEFORE UPDATE OF IMPORTE ON EB_MOVIMIENTOS
FOR EACH ROW
DECLARE
 PRAGMA AUTONOMOUS_TRANSACTION;
 IMPORTE_MEDIO NUMBER(8,2);
BEGIN
 IF :NEW.IMPORTE<0 THEN
  :NEW.IMPORTE:=:OLD.IMPORTE;
 END IF;
 SELECT AVG(IMPORTE) INTO IMPORTE_MEDIO FROM EB_MOVIMIENTOS
 WHERE CONCEPTO=:OLD.CONCEPTO;
 IF :NEW.IMPORTE>IMPORTE_MEDIO*1.2 THEN
  :NEW.IMPORTE:=IMPORTE_MEDIO;
 END IF;
END;

--4
CREATE OR REPLACE PROCEDURE EX_2018_4(DNI VARCHAR2)
AS
 NC VARCHAR2(25);
 AC VARCHAR2(35);
 SUMA_I NUMBER(8,2);
 SUMA_R NUMBER(8,2);
 SALDO NUMBER(8,2);
 CURSOR CUENTAS_CLIENTE IS SELECT * FROM EB_CUENTAS 
 WHERE CLITITULAR=DNI OR CLIAUTORIZADO=DNI;
BEGIN
 SELECT NOMCLI,APECLI INTO NC,AC FROM EB_CLIENTES WHERE DNICLI=DNI;
 DBMS_OUTPUT.PUT_LINE(AC||', '||NC);
 DBMS_OUTPUT.PUT_LINE('------ CUENTAS -----------');
 FOR F IN CUENTAS_CLIENTE LOOP
  SELECT SUM(IMPORTE) INTO SUMA_I FROM EB_MOVIMIENTOS WHERE TIPOMOV='I' AND
  NUMEROCTA=F.NUMEROCTA AND SUCURSAL=F.SUCURSAL;
  SELECT SUM(IMPORTE) INTO SUMA_R FROM EB_MOVIMIENTOS WHERE TIPOMOV='R' AND
  NUMEROCTA=F.NUMEROCTA AND SUCURSAL=F.SUCURSAL;
  SALDO:=SUMA_I-SUMA_R;
  DBMS_OUTPUT.PUT_LINE(F.NUMEROCTA||' '||F.SUCURSAL||' '||F.TIPO
  ||' '||F.FECHAAPERTURA||' '||SALDO);
 END LOOP;
EXCEPTION
 WHEN NO_DATA_FOUND THEN
  DBMS_OUTPUT.PUT_LINE('EL CLIENTE NO EXISTE');
END;

