BBDD INSTITUTO

--3
CREATE OR REPLACE PROCEDURE EJ3_INSTI(CAL I_ALUMNOS.CODAL%TYPE)
AS
CALU I_ALUMNOS.CODAL%TYPE;
NOM I_ALUMNOS.NOMBRE%TYPE;
APE I_ALUMNOS.APELLIDOS%TYPE;
CIU I_ALUMNOS.CIUDAD%TYPE;
FEC I_ALUMNOS.FECHANACIMIENTO%TYPE;
BEGIN
SELECT CODAL,NOMBRE,APELLIDOS,CIUDAD,FECHANACIMIENTO 
INTO CALU,NOM,APE,CIU,FEC FROM I_ALUMNOS WHERE CODAL=CAL;
DBMS_OUTPUT.PUT_LINE(CALU||' '||NOM||' '||APE||' '||CIU||' '||FEC);
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('EL ALUMNO NO EXISTE');
END;

EXECUTE EJ3_INSTI(1)

--4
CREATE OR REPLACE TRIGGER EJ4_INSTI
BEFORE UPDATE OR INSERT ON I_NOTAS
FOR EACH ROW
BEGIN
 IF :NEW.NOTA<0 THEN
  :NEW.NOTA:=-1*:NEW.NOTA;
 END IF;
  IF :NEW.FECHA>CURRENT_DATE THEN
  :NEW.FECHA:=CURRENT_DATE;
 END IF;
END;

INSERT INTO I_NOTAS VALUES (1,'GBD','26/05/2023',-8);

SELECT * FROM I_NOTAS;

--5
CREATE OR REPLACE PROCEDURE EJ5_INSTI(NAS I_ASIGNATURAS.NOMBRE%TYPE)
AS
 CURSOR C IS SELECT AL.CODAL,AL.NOMBRE AL_NOM,AL.APELLIDOS,ASI.NOMBRE AL_ASI,ASI.CURSO,ASI.NIVEL,N.FECHA,N.NOTA
 FROM I_ALUMNOS AL INNER JOIN I_NOTAS N ON AL.CODAL=N.CODAL INNER JOIN I_ASIGNATURAS ASI ON N.CODAS=ASI.CODAS
 WHERE ASI.NOMBRE=NAS ORDER BY AL.APELLIDOS,AL.NOMBRE;
BEGIN
 FOR F IN C LOOP
  DBMS_OUTPUT.PUT_LINE(F.CODAL||' '||F.AL_NOM||' '||F.APELLIDOS||' '||F.AL_ASI||' '||F.CURSO||' '||F.NIVEL||' '||
  F.FECHA||' '||F.NOTA);
 END LOOP;
END;

EXECUTE EJ5_INSTI('Aplicaciones Web')

--6
CREATE OR REPLACE PROCEDURE EJ6_INSTI
AS
 CURSOR C IS SELECT N.NOTA
 FROM I_ALUMNOS AL INNER JOIN I_NOTAS N ON AL.CODAL=N.CODAL INNER JOIN I_ASIGNATURAS ASI ON N.CODAS=ASI.CODAS;
BEGIN
 FOR F IN C LOOP
  IF F.NOTA*1.1<=10 THEN
   F.NOTA:=F.NOTA*1.1;
  END IF;
 END LOOP;
END;

EXECUTE EJ6_INSTI;