-- EXAMEN PLSQL JOSÉ MARÍA VIÚDEZ PARRA

--1
CREATE OR REPLACE FUNCTION EJ1_EX_2022_INSTITUTO(CP I_PROFESORES.CODPR%TYPE)
RETURN CHAR
AS
 APE I_PROFESORES.APELLIDOS%TYPE;
 NOM I_PROFESORES.NOMBRE%TYPE;
 DEP I_PROFESORES.DEPARTAMENTO%TYPE;
 SUE I_PROFESORES.SUELDO%TYPE;
 AÑOS_ANTIG NUMBER(2);
 ASIG_IMPAR NUMBER(2);
 CADENA CHAR(255);
BEGIN
 SELECT APELLIDOS,NOMBRE,DEPARTAMENTO,SUELDO,MONTHS_BETWEEN(CURRENT_DATE,FECHAALTA)/12 
 INTO APE,NOM,DEP,SUE,AÑOS_ANTIG FROM I_PROFESORES WHERE CODPR=CP;
 SELECT COUNT(CODAS) INTO ASIG_IMPAR FROM I_IMPARTE WHERE CODPR=CP GROUP BY CODPR;
 CADENA:=APE||', '||NOM||' – '||DEP||' – '||SUE||' – '||AÑOS_ANTIG||' – '||ASIG_IMPAR;
 RETURN CADENA;
 EXCEPTION 
 WHEN NO_DATA_FOUND THEN 
 DBMS_OUTPUT.PUT_LINE(' ');
END;

SELECT EJ1_EX_2022_INSTITUTO(2) FROM DUAL

--2
CREATE OR REPLACE PROCEDURE EJ2_EX_2022_INSTITUTO(
CAL I_ALUMNOS.CODAL%TYPE,
CAC I_MATRICULA.CURSO%TYPE
)
AS
 CALU I_ALUMNOS.CODAL%TYPE;
 NOM I_ALUMNOS.NOMBRE%TYPE;
 APE I_ALUMNOS.APELLIDOS%TYPE;
 CIU I_ALUMNOS.CIUDAD%TYPE;
 FEC I_ALUMNOS.FECHANACIMIENTO%TYPE;
 CURSOR ASIGNATURAS IS SELECT M.CODAS,A.NOMBRE,A.NIVEL,M.CURSO FROM I_ASIGNATURAS A 
 INNER JOIN I_MATRICULA M ON A.CODAS=M.CODAS WHERE A.CURSO=CAC AND M.CODAL=CAL;
BEGIN
 SELECT CODAL,NOMBRE,APELLIDOS,CIUDAD,FECHANACIMIENTO 
 INTO CALU,NOM,APE,CIU,FEC FROM I_ALUMNOS WHERE CODAL=CAL;
 DBMS_OUTPUT.PUT_LINE('DATOS DEL ALUMNO:');
 DBMS_OUTPUT.PUT_LINE(CALU||' '||NOM||' '||APE||' '||CIU||' '||FEC);
 DBMS_OUTPUT.PUT_LINE(' ');
 DBMS_OUTPUT.PUT_LINE('RELACIÓN DE ASIGNATURAS EN LAS QUE EL ALUMNO HA SIDO MATRICULADO EN DICHO CURSO ACADÉMICO:');
 FOR FILA_ASIGNATURAS IN ASIGNATURAS LOOP
  DBMS_OUTPUT.PUT_LINE(FILA_ASIGNATURAS.CODAS||' '||FILA_ASIGNATURAS.NOMBRE
  ||' '||FILA_ASIGNATURAS.NIVEL||' '||FILA_ASIGNATURAS.CURSO);
 END LOOP;
 EXCEPTION
 WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('EL ALUMNO NO EXISTE');
END;

EXECUTE EJ2_EX_2022_INSTITUTO(1,'1')

--3
CREATE OR REPLACE TRIGGER EJ3_EX_2022_INSTITUTO
BEFORE UPDATE OF SUELDO ON I_PROFESORES
FOR EACH ROW
DECLARE
 PRAGMA AUTONOMOUS_TRANSACTION;
 SUELDO_MEDIO_DEPART I_PROFESORES.SUELDO%TYPE;
BEGIN
 SELECT AVG(SUELDO) INTO SUELDO_MEDIO_DEPART FROM I_PROFESORES WHERE DEPARTAMENTO=:OLD.DEPARTAMENTO;
 IF :NEW.SUELDO>:OLD.SUELDO+SUELDO_MEDIO_DEPART/2 THEN
   :NEW.SUELDO:=:OLD.SUELDO+SUELDO_MEDIO_DEPART/2;
 END IF;
END;

--4
CREATE OR REPLACE PROCEDURE EJ4_EX_2022_INSTITUTO(FEC I_NOTAS.FECHA%TYPE)
AS
 CURSOR C IS SELECT N.CODAL,N.CODAS,AL.NOMBRE NOM_AL,AL.APELLIDOS APE_AL,ASI.NOMBRE NOM_ASI,N.NOTA 
 FROM I_ASIGNATURAS ASI INNER JOIN I_NOTAS N ON ASI.CODAS=N.CODAS INNER JOIN I_ALUMNOS AL ON N.CODAL=AL.CODAL 
 WHERE N.FECHA=FEC;
BEGIN
 FOR F IN C LOOP
  DBMS_OUTPUT.PUT_LINE(F.NOM_AL||' '||F.APE_AL||', '||F.NOM_ASI||': '||F.NOTA);
 END LOOP;
 EXCEPTION
 WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('EL ALUMNO NO EXISTE');
END;

EXECUTE EJ4_EX_2022_INSTITUTO('10/12/12');

--5
--1ª FORMA
CREATE OR REPLACE PROCEDURE EJ5_EX_2022_INSTITUTO(CPR I_PROFESORES.CODPR%TYPE)
AS
 CURSOR C1 IS SELECT I.CODAS,A.NOMBRE,A.NIVEL,I.CURSO FROM I_ASIGNATURAS A
 INNER JOIN I_IMPARTE I ON A.CODAS=I.CODAS WHERE I.CODPR=CPR;
 CURSOR C2 IS SELECT CODAL,NOMBRE,APELLIDOS,CIUDAD,FECHANACIMIENTO,CURSO FROM I_IMPARTE 
 NATURAL JOIN I_MATRICULA NATURAL JOIN I_ALUMNOS WHERE CODPR=CPR;
BEGIN
 DBMS_OUTPUT.PUT_LINE('RELACIÓN DE ASIGNATURAS QUE HA IMPARTIDO EL PROFESOR:');
 FOR F1 IN C1 LOOP
  DBMS_OUTPUT.PUT_LINE(F1.CODAS||' '||F1.NOMBRE
  ||' '||F1.NIVEL||' '||F1.CURSO);
 END LOOP;
 DBMS_OUTPUT.PUT_LINE(' ');
 DBMS_OUTPUT.PUT_LINE('LISTA DE ALUMNOS MATRICULADOS EN ESAS ASIGNATURAS EN ESOS CURSOS:');
 FOR F2 IN C2 LOOP
  DBMS_OUTPUT.PUT_LINE(F2.CODAL||' '||F2.NOMBRE
  ||' '||F2.APELLIDOS||' '||F2.CIUDAD||' '||F2.FECHANACIMIENTO||' '||F2.CURSO);
 END LOOP;
 EXCEPTION
 WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('EL PROFESOR NO EXISTE');
END;

EXECUTE EJ5_EX_2022_INSTITUTO(1)

--2ª FORMA
CREATE OR REPLACE PROCEDURE EJ5_EX_2022_INSTITUTO_1(CPR I_PROFESORES.CODPR%TYPE)
AS
 CAS VARCHAR2(6);
 CURSOR C1 IS SELECT I.CODAS,A.NOMBRE,A.NIVEL,I.CURSO FROM I_ASIGNATURAS A INNER JOIN I_IMPARTE I ON A.CODAS=I.CODAS 
 WHERE CODPR=CPR;
 CURSOR C2 IS SELECT M.CODAL,AL.NOMBRE,AL.APELLIDOS,AL.CIUDAD,AL.FECHANACIMIENTO,M.CURSO FROM I_MATRICULA M 
 INNER JOIN I_ALUMNOS AL ON M.CODAL=AL.CODAL WHERE M.CODAS=CAS;
BEGIN
 DBMS_OUTPUT.PUT_LINE('RELACIÓN DE ASIGNATURAS QUE HA IMPARTIDO EL PROFESOR:');
 FOR F1 IN C1 LOOP
  CAS:=F1.CODAS;
  DBMS_OUTPUT.PUT_LINE(' ');
  DBMS_OUTPUT.PUT_LINE(F1.CODAS||' '||F1.NOMBRE
  ||' '||F1.NIVEL||' '||F1.CURSO);
  DBMS_OUTPUT.PUT_LINE(' ');
  DBMS_OUTPUT.PUT_LINE('LISTA DE ALUMNOS MATRICULADOS EN ESAS ASIGNATURAS EN ESOS CURSOS:');
  FOR F2 IN C2 LOOP
  DBMS_OUTPUT.PUT_LINE(F2.CODAL||' '||F2.NOMBRE
  ||' '||F2.APELLIDOS||' '||F2.CIUDAD||' '||F2.FECHANACIMIENTO||' '||F2.CURSO);
  END LOOP;
 END LOOP;
 EXCEPTION
 WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('EL PROFESOR NO EXISTE');
END;

EXECUTE EJ5_EX_2022_INSTITUTO_1(1)
