CREATE TABLE LF_PERSONAS(
DNI CHAR(9) PRIMARY KEY,
NOMBRE VARCHAR2(30) NOT NULL,
DIRECCION VARCHAR2(50) NOT NULL,
TELEFONO CHAR(9) NULL,
SEXO CHAR(1) NOT NULL
);
CREATE TABLE LF_EQUIPOS (
CODIGO NUMERIC(2) PRIMARY KEY,
NOMBRE VARCHAR2(25) NOT NULL,
CIUDAD VARCHAR2(20) NOT NULL,
ESTADIO VARCHAR2(25) NOT NULL,
AFORO NUMERIC(6,0) NULL,
FECHA_FUNDACION DATE NOT NULL,
DNI_PRESIDENTE CHAR(9),
FOREIGN KEY (DNI_PRESIDENTE) REFERENCES LF_PERSONAS(DNI)
);