SELECT  FROM EMPLE WHERE DEPT_NO=20 ORDER BY APELLIDO;
SELECT  FROM EMPLE WHERE OFICIO='ANALISTA' ORDER BY DEPT_NO;
SELECT  FROM EMPLE WHERE OFICIO='ANALISTA' AND DEPT_NO=10 ORDER BY EMP_NO DESC;
SELECT  FROM ALUM0405; SELECT  FROM ALUM0405 WHERE POBLACION='GUADALAJARA'; SELECT APELLIDOS,NOMBRE FROM ALUM0405 WHERE POBLACION='GUADALAJARA'; SELECT DNI,NOMBRE,APELLIDOS,CURSO,NIVEL,CLASE FROM ALUM0405 ORDER BY APELLIDOS,NOMBRE;
SELECT NOMBRE_ALUMNO,(NOTA1+NOTA2+NOTA3)3 'NOTA_MEDIA 'FROM notas_alumnos;
SELECT ,(NOTA1+NOTA2+NOTA3)3 FROM notas_alumnos WHERE NOTA1=7 AND (NOTA1+NOTA2+NOTA3)36
SELECT  FROM EMPLE WHERE APELLIDO LIKE 'J%'
SELECT  FROM EMPLE WHERE APELLIDO LIKE '_R%'
SELECT  FROM EMPLE WHERE APELLIDO LIKE 'A%O%'
SELECT * FROM EMPLE WHERE OFICIO='ANALISTA' OR OFICIO='VENDEDOR' OR OFICIO='EMPLEADO'
SELECT * FROM EMPLE WHERE OFICIO IN ('ANALISTA','VENDEDOR','EMPLEADO')
SELECT * FROM EMPLE WHERE OFICIO!='ANALISTA' AND OFICIO!='VENDEDOR' AND OFICIO!='EMPLEADO'
SELECT * FROM EMPLE WHERE OFICIO NOT IN ('ANALISTA','VENDEDOR','EMPLEADO')
SELECT * FROM EMPLE WHERE SALARIO BETWEEN 1500 AND 2000
SELECT * FROM EMPLE WHERE SALARIO>=1500 AND SALARIO<=2000
SELECT * FROM EMPLE WHERE SALARIO NOT BETWEEN 1500 AND 2000
SELECT * FROM EMPLE WHERE SALARIO<=1500 OR SALARIO>=2000
SELECT * FROM EMPLE WHERE DEPT_NO=20 OR DEPT_NO=10 AND SALARIO>=2000
SELECT * FROM EMPLE WHERE OFICIO=(SELECT OFICIO FROM EMPLE WHERE APELLIDO='GIL')
SELECT * FROM EMPLE WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE LOC='MADRID' OR LOC='BARCELONA')
SELECT * FROM EMPLE WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE LOC IN ('MADRID','BARCELONA'))
SELECT * FROM EMPLE WHERE OFICIO IN (SELECT OFICIO FROM EMPLE WHERE APELLIDO='JIMENEZ')
SELECT * FROM EMPLE WHERE SALARIO=(SELECT SALARIO FROM EMPLE WHERE APELLIDO='FERNANDEZ')
SELECT EMP_NO,APELLIDO,SALARIO,DNOMBRE,LOC FROM EMPLE NATURAL JOIN DEPART;
SELECT EMP_NO,APELLIDO,SALARIO,DNOMBRE,LOC FROM EMPLE E, DEPART D WHERE E.`DEPT_NO`=D.`DEPT_NO`
SELECT * FROM ALUMNOS WHERE DNI= (SELECT DNI FROM NOTAS WHERE NOTA BETWEEN 7 AND 8 AND COD=(SELECT COD FROM asignaturas WHERE NOMBRE='FOL'))
SELECT * FROM asignaturas WHERE COD IN(SELECT COD FROM NOTAS WHERE NOTA>=5)
SELECT * FROM asignaturas WHERE COD IN(SELECT COD FROM NOTAS WHERE NOT NOTA<5)
