SELECT NOMBRE,PRECIOVENTA FROM PRODUCTOS WHERE PRECIOVENTA=(SELECT MAX(PRECIOVENTA) FROM PRODUCTOS)
SELECT NOMBRE FROM PRODUCTOS WHERE CODIGOPRODUCTO IN (SELECT CODIGOPRODUCTO FROM DETALLEPEDIDOS WHERE CANTIDAD=(SELECT MAX(CANTIDAD) FROM DETALLEPEDIDOS))
SELECT nombrecliente FROM CLIENTES C WHERE LIMITECREDITO> ALL (SELECT CANTIDAD FROM PAGOS WHERE CODIGOCLIENTE=C.CODIGOCLIENTE)
SELECT * FROM PRODUCTOS WHERE CantidadEnStock=(SELECT MAX(CANTIDADENSTOCK) FROM PRODUCTOS) OR CantidadEnStock=(SELECT MIN(CANTIDADENSTOCK) FROM PRODUCTOS)
