-- #TABLAS SQL
SELECT CIUDAD,TELEFONO FROM OFICINAS WHERE PAIS='EEUU';
SELECT NOMBRE,APELLIDO1,APELLIDO2,EMAIL FROM EMPLEADOS WHERE CODIGOJEFE=(SELECT CODIGOEMPLEADO FROM EMPLEADOS WHERE NOMBRE='ALBERTO' AND APELLIDO1='SORIA');
SELECT E.NOMBRE,E.APELLIDO1,E.APELLIDO2,E.EMAIL FROM EMPLEADOS E LEFT JOIN EMPLEADOS J ON E.CODIGOJEFE=J.CODIGOEMPLEADO WHERE J.NOMBRE='ALBERTO' AND J.APELLIDO1='SORIA'
SELECT PUESTO,NOMBRE,APELLIDO1,APELLIDO2 FROM EMPLEADOS WHERE PUESTO!='REPRESENTANTE VENTAS'
SELECT PUESTO,NOMBRE,APELLIDO1,APELLIDO2 FROM EMPLEADOS WHERE CODIGOEMPLEADO NOT IN (SELECT CodigoEmpleadoRepVentas FROM CLIENTES) AND PUESTO='REPRESENTANTE VENTAS'
SELECT COUNT(*) FROM CLIENTES
SELECT NOMBRECLIENTE FROM CLIENTES WHERE PAIS='SPAIN' OR PAIS='ESPAÑA' // PAIS IN (SPAIN,ESPAÑA)
SELECT PAIS,COUNT(*) FROM CLIENTES GROUP BY PAIS
SELECT CIUDAD,COUNT(*) FROM CLIENTES WHERE CIUDAD='MADRID'
SELECT COUNT(*) FROM CLIENTES WHERE CodigoEmpleadoRepVentas IN (SELECT CODIGOEMPLEADO FROM EMPLEADOS WHERE CodigoOficina IN (SELECT CODIGOOFICINA FROM OFICINAS WHERE CIUDAD='MADRID'))
SELECT CIUDAD,COUNT(*) FROM CLIENTES WHERE CIUDAD LIKE 'M%'
SELECT COUNT(*) FROM CLIENTES WHERE CodigoEmpleadoRepVentas IN (SELECT CODIGOEMPLEADO FROM EMPLEADOS WHERE CodigoOficina IN (SELECT CODIGOOFICINA FROM OFICINAS WHERE CIUDAD LIKE 'M%'))
SELECT CODIGOEMPLEADOREPVENTAS,COUNT(*) FROM CLIENTES GROUP BY CODIGOEMPLEADOREPVENTAS
SELECT CODIGOEMPLEADOREPVENTAS,COUNT(*) FROM CLIENTES C INNER JOIN EMPLEADOS E ON C.CODIGOEMPLEADOREPVENTAS=E.`CodigoEmpleado` GROUP BY CODIGOEMPLEADOREPVENTAS
SELECT CODIGOEMPLEADOREPVENTAS,COUNT(*) FROM CLIENTES WHERE CODIGOEMPLEADOREPVENTAS IS NULL
SELECT * FROM CLIENTES WHERE CODIGOEMPLEADOREPVENTAS IS NULL
SELECT * FROM PAGOS WHERE FECHAPAGO=(SELECT MIN(FECHAPAGO) FROM PAGOS) OR FECHAPAGO=(SELECT MAX(FECHAPAGO) FROM PAGOS)
SELECT * FROM PAGOS WHERE FECHAPAGO LIKE '2008%'
SELECT DISTINCT CODIGOCLIENTE FROM PAGOS WHERE YEAR(FECHAPAGO)=2008
SELECT DISTINCT CODIGOCLIENTE FROM PAGOS WHERE FECHAPAGO BETWEEN '2008-01-01' AND '2008-12-31'
SELECT DISTINCT ESTADO FROM PEDIDOS
SELECT CODIGOpedido,cOdigocliente,FechaEsperada,fechaentrega FROM PEDIDOS WHERE FechaEsperada<fechaentrega  
SELECT NumeroLinea,COUNT(*) FROM PRODUCTOS NATURAL JOIN detallepedidos GROUP BY NUMEROLINEA
SELECT CodigoProducto FROM PRODUCTOS NATURAL JOIN detallepedidos ORDER BY Cantidad DESC LIMIT 20
SELECT * FROM (SELECT CodigoProducto FROM PRODUCTOS NATURAL JOIN detallepedidos ORDER BY Cantidad DESC) WHERE ROWNUM<=20 #TABLA DERIVADA EN ORACLE
SELECT CODIGOpedido,cOdigocliente,FechaEsperada,fechaentrega FROM pedidos WHERE FechaEntrega<ADDDATE(FechaEsperada,INTERVAL 2 DAY)
SELECT CODIGOpedido,cOdigocliente,FechaEsperada,fechaentrega FROM pedidos WHERE FechaEntrega<DATE_SUB(FechaEsperada,INTERVAL 2 DAY)
SELECT SUM(cantidad) FROM pagos ;
SELECT SUM(PRECIOVENTA-PrecioProveedor),SUM(CANTIDAD*PrecioUnidad) FROM productos NATURAL JOIN detallepedidos
SELECT CIUDAD,TELEFONO FROM OFICINAS WHERE PAIS='EEUU';
SELECT NOMBRE,APELLIDO1,APELLIDO2,EMAIL FROM EMPLEADOS WHERE CODIGOJEFE=(SELECT CODIGOEMPLEADO FROM EMPLEADOS WHERE NOMBRE='ALBERTO' AND APELLIDO1='SORIA');
SELECT E.NOMBRE,E.APELLIDO1,E.APELLIDO2,E.EMAIL FROM EMPLEADOS E LEFT JOIN EMPLEADOS J ON E.CODIGOJEFE=J.CODIGOEMPLEADO WHERE J.NOMBRE='ALBERTO' AND J.APELLIDO1='SORIA'
SELECT PUESTO,NOMBRE,APELLIDO1,APELLIDO2 FROM EMPLEADOS WHERE PUESTO!='REPRESENTANTE VENTAS'
SELECT PUESTO,NOMBRE,APELLIDO1,APELLIDO2 FROM EMPLEADOS WHERE CODIGOEMPLEADO NOT IN (SELECT CodigoEmpleadoRepVentas FROM CLIENTES) AND PUESTO='REPRESENTANTE VENTAS'
SELECT COUNT(*) FROM CLIENTES
SELECT NOMBRECLIENTE FROM CLIENTES WHERE PAIS='SPAIN' OR PAIS='ESPAÑA' // PAIS IN (SPAIN,ESPAÑA)
SELECT PAIS,COUNT(*) FROM CLIENTES GROUP BY PAIS
SELECT CIUDAD,COUNT(*) FROM CLIENTES WHERE CIUDAD='MADRID'
SELECT COUNT(*) FROM CLIENTES WHERE CodigoEmpleadoRepVentas IN (SELECT CODIGOEMPLEADO FROM EMPLEADOS WHERE CodigoOficina IN (SELECT CODIGOOFICINA FROM OFICINAS WHERE CIUDAD='MADRID'))
SELECT CIUDAD,COUNT(*) FROM CLIENTES WHERE CIUDAD LIKE 'M%'
SELECT CODIGOEMPLEADOREPVENTAS,COUNT(*) FROM CLIENTES GROUP BY CODIGOEMPLEADOREPVENTAS
SELECT CODIGOEMPLEADOREPVENTAS,COUNT(*) FROM CLIENTES C INNER JOIN EMPLEADOS E ON C.CODIGOEMPLEADOREPVENTAS=E.`CodigoEmpleado` GROUP BY CODIGOEMPLEADOREPVENTAS
SELECT CODIGOEMPLEADOREPVENTAS,COUNT(*) FROM CLIENTES WHERE CODIGOEMPLEADOREPVENTAS IS NULL
SELECT COUNT(*) FROM CLIENTES WHERE CODIGOEMPLEADOREPVENTAS IS NULL
SELECT * FROM PAGOS WHERE FECHAPAGO=(SELECT MIN(FECHAPAGO) FROM PAGOS) OR FECHAPAGO=(SELECT MAX(FECHAPAGO) FROM PAGOS)
SELECT DISTINCT CODIGOCLIENTE FROM PAGOS WHERE YEAR(FECHAPAGO)=2008
SELECT DISTINCT CODIGOCLIENTE FROM PAGOS WHERE FECHAPAGO BETWEEN '2008-01-01' AND '2008-12-31'
SELECT DISTINCT ESTADO FROM PEDIDOS
SELECT CODIGOpedido,cOdigocliente,FechaEsperada,fechaentrega FROM PEDIDOS WHERE FechaEsperada<fechaentrega  
SELECT NumeroLinea,COUNT(*) FROM detallepedidos GROUP BY NUMEROLINEA
SELECT CodigoProducto,SUM(CANTIDAD) FROM detallepedidos GROUP BY CODIGOPRODUCTO ORDER BY SUM(CANTIDAD) DESC LIMIT 20
SELECT CODIGOpedido,cOdigocliente,FechaEsperada,fechaentrega FROM pedidos WHERE FechaEntrega>=ADDDATE(FechaEsperada,INTERVAL 2 DAY)
SELECT CODIGOpedido,cOdigocliente,FechaEsperada,fechaentrega FROM pedidos WHERE FechaEsperada<=SUBDATE(FechaEntrega,INTERVAL 2 DAY)
SELECT SUM(cantidad) FROM pagos ;
SELECT ROUND(SUM(CANTIDAD*PrecioUnidad)*121/100,2) FROM detallepedidos
SELECT SUM(CANTIDAD*PrecioUnidad) “TOTAL FACTURADO NETO”, ROUND(SUM(CANTIDAD*PrecioUnidad)*21/100,2)“IVA”, SUM(CANTIDAD*PrecioUnidad) + ROUND(SUM(CANTIDAD*PrecioUnidad)*21/100,2)  “TOTAL FACTURADO CON IVA” FROM detallepedidos
SELECT CODIGOPRODUCTO,ROUND(SUM(CANTIDAD*PrecioUnidad)*121/100,2) FROM detallepedidos WHERE CODIGOPRODUCTO LIKE "FR%" GROUP BY CodigoProducto

