-- #TABLAS ORACLE = TABLAS JSQL
SELECT COUNT(*) FROM CLIENTES #SQL Y ORACLE
SELECT PAIS,COUNT(*) FROM CLIENTES GROUP BY PAIS #SQL Y ORACLE
SELECT AVG(CANTIDAD) FROM PAGOS WHERE YEAR(FECHAPAGO)='2008' C
SELECT AVG(CANTIDAD FROM PAGOS WHERE FECHAPAGO=(SELECT TO_CHAR(TO_DATE('27/01/22','yyyy') FROM DUAL #ORACLE
SELECT ESTADO,COUNT(*) FROM PEDIDOS GROUP BY ESTADO ORDER BY COUNT(*) DESC #SQL Y ORACLE
SELECT MAX(PRECIOVENTA),MIN(PRECIOVENTA) FROM PRODUCTOS
SELECT LIMITECREDITO,NOMBRECLIENTE FROM CLIENTES WHERE LIMITECREDITO=(SELECT MAX(LIMITECREDITO) FROM CLIENTES)
SELECT NOMBRE,APELLIDO1,PUESTO FROM EMPLEADOS WHERE CODIGOEMPLEADO NOT IN
(SELECT CODIGOEMPLEADOREPVENTAS FROM CLIENTES)
SELECT NOMBRECLIENTE,NOMBRE,APELLIDO1 FROM CLIENTES C INNER JOIN EMPLEADOS E ON C.CODIGOEMPLEADOREPVENTAS=E.CODIGOEMPLEADO
SELECT NOMBRECLIENTE,NOMBRE,APELLIDO1 FROM CLIENTES C INNER JOIN EMPLEADOS E ON C.CODIGOEMPLEADOREPVENTAS=E.CODIGOEMPLEADO
WHERE CODIGOCLIENTE NOT IN(SELECT CODIGOCLIENTE FROM PAGOS)
SELECT NOMBRE,SUM(CANTIDAD)"UNIDADES VENDIDAS",SUM(CANTIDAD*PRECIOUNIDAD)*1.21"TOTAL FACTURADO CON IVA",SUM(CANTIDAD*PRECIOUNIDAD)"TOTAL FACTURADO" 
FROM DETALLEPEDIDOS NATURAL JOIN PRODUCTOS
GROUP BY CODIGOPRODUCTO HAVING SUM(CANTIDAD*PRECIOUNIDAD)>3000 #SQL
SELECT NOMBRE,SUM(CANTIDAD)"UNIDADES VENDIDAS",SUM(CANTIDAD*PRECIOUNIDAD)*1.21"TOTAL FACTURADO CON IVA",SUM(CANTIDAD*PRECIOUNIDAD) "TOTAL FACTURADO" 
FROM JDETALLEPEDIDOS NATURAL JOIN JPRODUCTOS
GROUP BY CODIGOPRODUCTO,NOMBRE HAVING SUM(CANTIDAD*PRECIOUNIDAD)>3000 #ORACLE
SELECT DISTINCT OFICINAS.CIUDAD FROM OFICINAS NATURAL JOIN EMPLEADOS E
INNER JOIN CLIENTES C ON E.CODIGOEMPLEADO=C.CODIGOEMPLEADOREPVENTAS WHERE C.CIUDAD='FUENLABRADA'
