SELECT DISTINCT NOMBRECLIENTE,COUNT(CODIGOPEDIDO) "NUMERO PEDIDOS" FROM CLIENTES NATURAL JOIN PEDIDOS GROUP BY CODIGOCLIENTE
SELECT SUM(CANTIDAD*PRECIOUNIDAD) "TOTAL FACTURADO" FROM DETALLEPEDIDOS WHERE YEAR(FECHAPEDIDO)=2000;
SELECT DISTINCT NOMBRECLIENTE FROM CLIENTES NATURAL JOIN PEDIDOS WHERE YEAR(FECHAPEDIDO)='2008'
SELECT C.NOMBRECLIENTE,E.NOMBRE,E.APELLIDO1 FROM CLIENTES C INNER JOIN EMPLEADOS E ON C.CODIGOEMPLEADOREPVENTAS=E.CODIGOEMPLEADO WHERE CODIGOCLIENTE NOT IN (SELECT CODIGOCLIENTE FROM PAGOS)
SELECT C.NOMBRECLIENTE,E.NOMBRE,O.CIUDAD FROM CLIENTES C INNER JOIN EMPLEADOS E ON C.CODIGOEMPLEADOREPVENTAS=E.CODIGOEMPLEADO INNER JOIN OFICINAS O ON O.CODIGOOFICINA=E.CODIGOOFICINA
SELECT NOMBRE,APELLIDO1,APELLIDO2,PUESTO,CODIGOOFICINA FROM EMPLEADOS WHERE PUESTO!='REPRESENTANTE VENTAS'
SELECT 	CODIGOOFICINA,COUNT(CODIGOEMPLEADO),CIUDAD FROM EMPLEADOS NATURAL JOIN OFICINAS GROUP BY CODIGOOFICINA,CIUDAD
SELECT E.NOMBRE "NOMBRE EMPLEADO",J.NOMBRE "NOMBRE JEFE" FROM EMPLEADOS E INNER JOIN EMPLEADOS J ON E.`CodigoJefe`=J.`CodigoEmpleado`
SELECT NOMBRE,APELLIDO1,APELLIDO2,PUESTO,CODIGOOFICINA FROM EMPLEADOS WHERE CODIGOEMPLEADO NOT IN (SELECT CodigoEmpleadoRepVentas FROM clientes)
SELECT GAMA,AVG(CANTIDADENSTOCK) FROM PRODUCTOS GROUP BY GAMA
SELECT DISTINCT O.`Ciudad`,C.`NombreCliente` FROM OFICINAS O INNER JOIN CLIENTES C ON O.`Ciudad`=C.`Ciudad`
SELECT NOMBRECLIENTE,CIUDAD FROM CLIENTES WHERE CIUDAD NOT IN (SELECT CIUDAD FROM OFICINAS) ORDER BY CIUDAD
SELECT * FROM CLIENTES WHERE CODIGOCLIENTE IN ((SELECT CODIGOCLIENTE FROM PAGOS WHERE CANTIDAD=(SELECT MAX(CANTIDAD) FROM PAGOS) OR CANTIDAD=(SELECT MIN(CANTIDAD) FROM PAGOS)))
SELECT CODIGOPEDIDO,SUM(CANTIDAD*PRECIOUNIDAD) FROM DETALLEPEDIDOS GROUP BY CodigoPedido
SELECT CODIGOCLIENTE FROM PEDIDOS NATURAL JOIN DETALLEPEDIDOS  WHERE YEAR(FECHAPEDIDO)='2008' GROUP BY CODIGOPEDIDO, CODIGOCLIENTE HAVING SUM(CANTIDAD*PRECIOUNIDAD)>2000
SELECT NOMBRECLIENTE,ESTADO,COUNT(CODIGOPEDIDO) FROM PEDIDOS NATURAL JOIN CLIENTES GROUP BY CODIGOCLIENTE,NOMBRECLIENTE,ESTADO
SELECT * FROM CLIENTES WHERE CODIGOCLIENTE IN (SELECT CODIGOCLIENTE FROM PEDIDOS NATURAL JOIN DETALLEPEDIDOS GROUP BY CODIGOPRODUCTO,CODIGOCLIENTE HAVING SUM(CANTIDAD)>200)
