CREATE DATABASE SISTEMA_PEDIDOS;
USE SISTEMA_PEDIDOS;
CREATE TABLE PROVEEDORES(
CIF VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(12) NULL,
PERSONA_CONTACTO VARCHAR(30) NULL
);
CREATE TABLE ARTICULOS(
REF DECIMAL(4) PRIMARY KEY,
NOMBRE VARCHAR(40) NOT NULL,
FAMILIA DECIMAL(2) NOT NULL,
STOCK DECIMAL(4) NOT NULL,
PRECIO DECIMAL(6,2) NOT NULL,
OBSERVACIONES VARCHAR(255)
);
CREATE TABLE FAMILIAS(
REF DECIMAL(2) PRIMARY KEY,
DESCRIPCION VARCHAR(50) NOT NULL
);
CREATE TABLE PEDIDOS(
REF DECIMAL(10) PRIMARY KEY,
FECHA DATE NOT NULL,
CIF_PROVEEDOR VARCHAR(10) NOT NULL,
ESTADO VARCHAR(30) NOT NULL
);
CREATE TABLE DETALLES_PEDIDOS(
REF_PEDIDO DECIMAL(10) NOT NULL,
LINEA DECIMAL(2) NOT NULL,
REF_ARTICULO DECIMAL(4) NOT NULL,
UNIDADES DECIMAL(5) NOT NULL,
PRIMARY KEY (REF_PEDIDO,LINEA)
);
ALTER TABLE ARTICULOS ADD 
CONSTRAINT FK_FAMILIA
FOREIGN KEY(FAMILIA) REFERENCES
FAMILIAS(REF) ON DELETE CASCADE;
ALTER TABLE PEDIDOS ADD 
FOREIGN KEY(CIF_PROVEEDOR) REFERENCES
PROVEEDORES(CIF) ON DELETE CASCADE;
ALTER TABLE DETALLES_PEDIDOS
ADD FOREIGN KEY(REF_PEDIDO) REFERENCES PEDIDOS(REF) ON DELETE CASCADE,
ADD FOREIGN KEY(REF_ARTICULO) REFERENCES ARTICULOS(REF) ON DELETE CASCADE;
ALTER TABLE PROVEEDORES
MODIFY DIRECCION VARCHAR(60);
ALTER TABLE ARTICULOS
ADD FECHA_ALTA DATE;
ALTER TABLE ARTICULOS 
ADD CONSTRAINT CHK_STOCK CHECK (STOCK>=0);
/*INSERT INTO FAMILIAS VALUES (1,'ALIMENTACION');
INSERT INTO ARTICULOS VALUES (1,'LATA ATUN CALVO',1,100,0.33,NULL,'2019-11-15');*/
ALTER TABLE PROVEEDORES ADD REF_INTERNA VARCHAR(15) UNIQUE AFTER CIF;
ALTER TABLE FAMILIAS RENAME COLUMN DESCRIPCION TO NOMBRE;
ALTER TABLE ARTICULOS DROP COLUMN OBSERVACIONES;