--BBDD JARDINERIA

--EJ 1
CREATE OR REPLACE PROCEDURE GAMAS_PRODUCTOS
AS
 TOTAL_PRODUCTOS_GAMA NUMBER(4);
 SUMA_PRECIOS NUMBER(8,2);
 CURSOR C IS SELECT * FROM JGAMASJPRODUCTOS ORDER BY GAMA;
BEGIN
 FOR F IN C LOOP
  SELECT SUM(PRECIOVENTA),COUNT(CODIGOPRODUCTO) INTO SUMA_PRECIOS,TOTAL_PRODUCTOS_GAMA
  FROM JPRODUCTOS WHERE GAMA=F.GAMA;
  DBMS_OUTPUT.PUT_LINE(F.GAMA||' '||F.DESCRIPCIONTEXTO||' '||SUMA_PRECIOS||' '||
  TOTAL_PRODUCTOS_GAMA);
 END LOOP;
END;

EXECUTE GAMAS_PRODUCTOS;

SELECT * FROM JPRODUCTOS;


--EJ 2
CREATE OR REPLACE PROCEDURE INCREMENTO_PAGOS
AS
 CURSOR C IS SELECT ROWID,CANTIDAD FROM JPAGOS WHERE FECHAPAGO>CURRENT_DATE;
 SUBIDA NUMBER(6,2);
 TOTAL NUMBER(10,2) DEFAULT 0;
BEGIN
 FOR F IN C LOOP
  COMMIT;
  SUBIDA:=F.CANTIDAD*0.05;
  UPDATE JPAGOS SET CANTIDAD=CANTIDAD+SUBIDA WHERE ROWID=F.ROWID;
  TOTAL:=TOTAL+SUBIDA;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PAGOS ACTUALIZADOS: '||C%ROWCOUNT);
  DBMS_OUTPUT.PUT_LINE('IMPORTE TOTAL DE INCREMENTO: '||TOTAL);
 END LOOP;
END;

EXECUTE INCREMENTO_PAGOS;

--EJ 3
CREATE OR REPLACE TRIGGER ACTUALIZAR_COD_PED_EN_DETALLEPEDIDOS
AFTER UPDATE OF CODIGOPEDIDO ON JPEDIDOS
FOR EACH ROW
BEGIN
 UPDATE JDETALLEPEDIDOS SET CODIGOPEDIDO=:NEW.CODIGOPEDIDO WHERE CODIGOPEDIDO=:OLD.CODIGOPEDIDO;
END;

UPDATE JPEDIDOS SET CODIGOPEDIDO=200 WHERE CODIGOPEDIDO=10

SELECT * FROM JPEDIDOS
SELECT * FROM JDETALLEPEDIDOS

ROLLBACK

--BBDD NBA

--EJ 1



--EJ 2



--EJ 3




