--EJ 1
CREATE OR REPLACE PROCEDURE SUBIDA_SALARIO
AS
    CURSOR C1 IS SELECT ROWID,SALARIO,DEPT_NO FROM EMPLE;
    SALARIO_MEDIO EMPLE.SALARIO%TYPE;
BEGIN
    FOR I IN C1 LOOP
        SELECT AVG(SALARIO) INTO SALARIO_MEDIO FROM EMPLE WHERE DEPT_NO=I.DEPT_NO;
        IF I.SALARIO<SALARIO_MEDIO THEN
            UPDATE EMPLE SET SALARIO=SALARIO_MEDIO WHERE ROWID=I.ROWID;
        END IF;
    END LOOP;
END;

EXECUTE SUBIDA_SALARIO;

--EJ 2
CREATE OR REPLACE PROCEDURE AUMENTO_LIMITE_CREDITO(PORCENTAJE NUMBER)
AS
    CURSOR CLIENTES_AFECTADOS IS SELECT CODIGOCLIENTE FROM JPAGOS 
    GROUP BY CODIGOCLIENTE HAVING SUM(CANTIDAD)>20000;
    IMPORTE_PAGO JPAGOS.CANTIDAD%TYPE;
BEGIN
    FOR F IN CLIENTES_AFECTADOS LOOP
        UPDATE JCLIENTES SET LIMITECREDITO=LIMITECREDITO+
        (LIMITECREDITO*PORCENTAJE/100)
        WHERE CODIGOCLIENTE=F.CODIGOCLIENTE;
        COMMIT;
    END LOOP;
END;

EXECUTE AUMENTO_LIMITE_CREDITO(5);

--EJ 3
CREATE OR REPLACE PROCEDURE LISTAR_JUGADORES(CONF VARCHAR2)
AS
    CURSOR JUG IS SELECT JUGADOR,NOMBRE_EQUIPO,
    AVG(REBOTES_POR_PARTIDO) MEDIA_REBOTES_JUGADOR
    FROM JUGADORES J INNER JOIN EQUIPOS E ON J.NOMBRE_EQUIPO=E.NOMBRE
    INNER JOIN ESTADISTICAS S ON J.CODIGO=S.JUGADOR
    WHERE CONFERENCIA=CONF GROUP BY JUGADOR,NOMBRE_EQUIPO;
    MEDIA_REBOTES_EQUIPO ESTADISTICAS.REBOTES_POR_PARTIDO%TYPE;
    NOM JUGADORES.NOMBRE%TYPE;
    PROC JUGADORES.PROCEDENCIA%TYPE;
    ALT JUGADORES.ALTURA%TYPE;
    PES JUGADORES.PESO%TYPE;
    POS JUGADORES.POSICION%TYPE;
BEGIN
    FOR F IN JUG LOOP
        SELECT AVG(REBOTES_POR_PARTIDO) INTO MEDIA_REBOTES_EQUIPO 
        FROM ESTADISTICAS WHERE JUGADOR IN
        (SELECT CODIGO FROM JUGADORES WHERE NOMBRE_EQUIPO=F.NOMBRE_EQUIPO);
        IF F.MEDIA_REBOTES_JUGADOR>MEDIA_REBOTES_EQUIPO THEN
            SELECT NOMBRE,PROCEDENCIA,ALTURA,PESO,POSICION INTO NOM,PROC,ALT,PES,POS 
            FROM JUGADORES WHERE CODIGO=F.JUGADOR;
            DBMS_OUTPUT.PUT_LINE(F.JUGADOR||' '||NOM||' '||PROC||' '||
            ALT||' '||PES||' '||POS||' '||F.NOMBRE_EQUIPO
            ||' '||F.MEDIA_REBOTES_JUGADOR||' '||MEDIA_REBOTES_EQUIPO);
        END IF;
    END LOOP;
END;

EXECUTE LISTAR_JUGADORES('East');