--EJ 1



--EJ2 OPOSICIONES

CREATE TABLE OPOSITORES(
    DNI VARCHAR2(9) PRIMARY KEY,
    APELLIDOS VARCHAR2(40) NOT NULL,
    NOMBRE VARCHAR2(25) NOT NULL,
    N_OPOSITOR NUMBER(3) DEFAULT NULL
)

INSERT INTO OPOSITORES VALUES ('111111122','PEREZ ALVAREZ','JOSE MARIA',NULL)

SELECT * FROM OPOSITORES WHERE APELLIDOS>='H' ORDER BY APELLIDOS,NOMBRE;
SELECT * FROM OPOSITORES WHERE APELLIDOS<'H' ORDER BY APELLIDOS,NOMBRE;


--CUANDO TENEMOS QUE TRATAR TODAS LAS FILAS DE LA 
TABLA SE PODRÁ UTILIZAR EL BUCLE FOR DEL CURSOR
NO LO UTILIZAREMOS CUANDO NOS PIDAN TRATAR POR EJEMPLO,
LAS 5 PRIMERAS FILAS().

CREATE OR REPLACE PROCEDURE ASIGNAR_NUMERO_OPOSITOR(LETRA CHAR)
AS
 CURSOR C1 IS SELECT ROWID FROM OPOSITORES WHERE APELLIDOS>=LETRA ORDER BY APELLIDOS,NOMBRE;
 CURSOR C2 IS SELECT ROWID FROM OPOSITORES WHERE APELLIDOS<LETRA ORDER BY APELLIDOS,NOMBRE;
 NUMERO NUMBER(4) DEFAULT 1;
BEGIN
 FOR FC1 IN C1 LOOP
  UPDATE OPOSITORES SET N_OPOSITOR=NUMERO WHERE ROWID=FC1.ROWID;
  NUMERO:=NUMERO+1;
  COMMIT;
 END LOOP;
 FOR FC2 IN C2 LOOP
  UPDATE OPOSITORES SET N_OPOSITOR=NUMERO WHERE ROWID=FC2.ROWID;
  NUMERO:=NUMERO+1;
  COMMIT;
 END LOOP;
END;

EXECUTE ASIGNAR_NUMERO_OPOSITOR('H');

SELECT * FROM OPOSITORES ORDER BY APELLIDOS,NOMBRE;

--EJ 3 ANTIGUEDAD

--EN ESTE CASO, AL ATENDER A LOS 2 EMPRESARIOS CON MAS ANTIGUEDAD,
NO PODREMOS UTILIZAR EL BUCLE FOR PARA EL CURSOR

CREATE OR REPLACE PROCEDURE SUBIDA_SALARIO_EMPLE(ND EMPLE.DEPT_NO%TYPE)
AS
 CURSOR C IS SELECT ROWID,DEPT_NO,SALARIO FROM EMPLE WHERE DEPT_NO=ND ORDER BY FECHA_ALT;
 SUBIDA NUMBER(8,2);
 F C%ROWTYPE;
BEGIN
 OPEN C;
 LOOP
 FETCH C INTO F;
 EXIT WHEN C%NOTFOUND OR C%ROWCOUNT>2;
  SUBIDA:=F.SALARIO*15/100;
  IF F.SALARIO<3000 THEN
   UPDATE EMPLE SET SALARIO=SALARIO+SUBIDA WHERE ROWID=F.ROWID;
  END IF;
  END LOOP;
 CLOSE C;
END;

EXECUTE SUBIDA_SALARIO_EMPLE(30);

SELECT * FROM EMPLE WHERE DEPT_NO=30 ORDER BY FECHA_ALT

--EJ 4







